name: check-laptimesim
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run lap time simulation test
      run: |
        pytest test_laptimesim.py
